language: java

jdk: oraclejdk8

cache:
  directories:
    - ~/.m2/repository
 
before_install:
  #- sudo apt-get update -q
  #- sudo apt-get install gnupg2
  #- sudo apt-get install gnupg-agent
 
install: 
  - echo "default-key 388E94D5" >> ~/.gnupg/gpg.conf
  - mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:   
  #- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script: mvn test -P !build-extras -B
   
after_success:
  - build/before-deploy.sh
  - build/deploy.sh
  
# configure notifications (email, IRC, campfire etc)
# check results at https://webchat.freenode.net/
notifications:
  irc: "irc.freenode.org#deepviolet"
  template:
      - '%{repository_slug}#%{build_number} (%{branch}) %{message} %{build_url}'