
language: java

jdk: oraclejdk8

sudo: true

cache:
  directories:
    - ~/.m2/repository
 
before_install:
  - sudo apt-get update -q
  #- sudo apt-get install gnupg2
  - sudo apt-get install gnupg-agent

install: 
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: 
- mvn test -B
   
after_success:
  - build/before-deploy.sh
  - build/deploy.sh
  
# configure notifications (email, IRC, campfire etc)
# check results at https://webchat.freenode.net/
notifications:
  irc: "irc.freenode.org#deepviolet"
  template:
      - '%{repository_slug}#%{build_number} (%{branch}) %{message} %{build_url}'
