language: java

jdk: oraclejdk8

cache:
  directories:
    - ~/.m2/repository

env:
  global:
   # GH_TOKEN
   secure: "ejbUqrRdKFPHVGXVDdu15z5GYS6sY2h+UQT48Jvr6p6CC3Ta6sQajvRzBc3DQP+KKXyiFryNN5fBhF0UezoElQ1V1eD4I82JDqF7HKmpk1nJnoLkdYQjbIEvTv7fRSs+IGpL62zYZUMR2/Iy+V32qECjUCEvnCHPRHaTnKDUlegGDEuBKyb7YGEzzxMRQWXJkd2xrR0tcaGYArtnAXtOH4sYSATFZB7UDiq1hRvX4eB5KVyKEVpHM45gnhccoGXkeeTy3m5KWxHypF7tK3pbe1mJejX4EURCER/hGrcS8xNzRmBbAhuk/KwAUCGo7AjOa5g301wp6n61Aen5sG4g+NMCjkUc0GmCDZ1/k/rH+DhXPmhI0X0cMG/BKtCdVbYDtFh03RCjwfxvxr3kjoXgz/rGBA14otzwnf2Ct9Q2VYiBFKCFm254fFgdlSu9DN53kyUIGSwXXxtj7+kExatpIMIQ22wiloWdZUQFk+J8eOGdfUzBgPc3Xe/HuNGI+G/Y6RWVhXY49xOmn6kHNSGj4ajyki8U0QthrEJ54mTQ+ZSAVtTx1BxGbOpN4MTg4UhLNv0vATi+a1lESCfu7Sn+XRRULPryeHFgSeLIsRxNjMics2Eg3KnDmKH8XOtmxj3v5WigZ+kI159C1h9nSJ4KvdrFvY8K/qXyM2lL77Fh4Bg="
   # OSSRH_USER
   secure: "LZLEMadHaJf9Cvl99vRAqt+e8gA/sfJLwokhV5+qQKF18tVUoP/HKkmg6hvbYRYS3YqKKLnC6GXmEZFnbbLzgk+eZWWu4jtLSzbzip78NVkZFVDHznAZQZldSwTpIkmDAjY/xekdXCjU1hAuXlHxfLFdf3SwsgUjXiLcgT4Mky84MqvKcH0o054awQ0NK2Y8Oxq6NAz0nt5ol7cMmRE/hhOZztShlULlKRjP3hHMmDigQlhobMvc7sZSfmC5DrOYPZQmZWlN0u7G8ONITM0gR4DAPaNpgYRLYlLLSn7tK4U0HDd97msWQwuui3mAwRL91rQ6dzAICvYQGlz+z2ZEROHFSDYByyLXL3W8LNY0KnMzMMRqhi02U2q9+PKp3j083gcIwYwhChPvqL/uwxDNUW3RsXylzGwvKVsIFFWVtHh7CsvgJaOyYEYtDnaHTpLcqGyJgFaxrqJZeyBB7TVIks8aIhXvLFZCM8RbkF90o/rBJ4U3cN5iwyIulCZ3Qv/+embVW6M86rz4tnWTf0aHE4hh/zCZ2GPrdCQPz6ZIBjVWUtSe6IvCYP+64LCgTi8aVFpga0Vnfz/w2DxXkRIoPF5jQtoOdMwzVh6e7tl1xmP9Q4yJTLeHbSx1b8h56Rx3RwzAxSmIeJ/9AqgUS2l9+EegCpKc+Jwy82vZKGO6KzA="
   # OSSRH_PASS
   secure: "ajZHBBCYFAQsehG8qPet01mgCSMPPKhLQeHbDFj/EBJ3/Zdij1/hkF6jY+0H5c52ui1J0PX/XggtPYytC607mjTRTrt009dhJ6180lLKhWxM8o6n1X+whzZMwOO1a/0YXedhjLjfkxU4XOkd2LtT16BLUTXQ83/vC5kHOqlc4ZlfrBFflHZuxB3DgB3UNYAiGkY5k6q0ECLeG3DkR/NIjOvufFijbS47ikDr0fhNfYjU/Ai1H3DPhO3XVXTkU85GOi31jVdHeEttmczmYiILUgmuCKLwTsMwrBjYSnLms2TpsqVD26doinw6xzGHHyhCvDJb0AF/IkJ8o6i5cbAEnSAfn3l8DsOxbvz0xxgTA7d7cUZ2pwlCDQDsNMSzfAh3tFCHM+D5DPC1PKwgfr9OVsnQo+9FPaaLDzr0rrSNv988R98vB1T+kcfV/b3QeA7AA+A0IstuevoR/ok9jOfyF5ST0tBORPW5PKEkf3iJCZiSbo1aU/fNhC8Sf+65j7rMJ2z7aInCcZhjrGwLDVNkg1zQZCso6p7op160V0i/r4kEbCWnkvxBHym4zGlQrrUMtigzjMFt4/R9KwITuXXSKUishbngiLlLDTd1rbv/jwBpJL+6C5KZExZGWnIdvDGoCURcGfNCH75aAo746aYQLNrMmbgD9JP/H5w8PRFyLHk="
   # OPENSSL_ENCRYPT_KEY
   secure: "ZX6JY6uiu4hp/EPVb+o7Gx7393FhFRR6o9JI/jBXpJ6+121lP6D5A7ZK94HSZXt6mvnU5tJcQPPZlNmq/Y94+c+pnmEfz+T3yyh1D1u4NEV1ySegiugxCIoCJIQnZIf17BXFRUIizj8m+ycGYKQat4PE7KvzzC6utwH5D6JpJSgSzma0NVdNp0wfAku/RSD94ZlZ7v+ssqzk3k2LiIhyOMOM1m2649yTWXH8IRu8SUeXOxp9zzWMktfBJ+zTj5nBl6Ee3m0v/70Nr6vhls5cqD28fpYKlo3RGK3w+zqUuXtIgCB9/NJDP0KJglchLOgyarwaj8B+DA1fZFyu1mT9GlGml0hBMhOMz1Wva/JrphZfqZ9CTaOVLXYz90nwj+1yamz4sVs2aMRXUjk4wYgLzbVDpbb6YOKRjimFfeY3eOmzIFgGMeMxF235ZEvbQqgz8T4R8YooMvEZQY6zMoUjpEypsndcW3MI8G3wwApxOO7hejvtrwr+lzWby/pC+wgWlphl0wHLwA30XI/r5uwSVG/41ONrKr4aH9kNiteJjAADjhYcF6oNvESjF3qKzjfsTzfYal862GXK3MyKi14+lulCAOU+9UFy10GLTpE3kCNDuAW+xMpQ1j1GbzFkInH7vUJGgZq8eWedpM1i13uu/3Iyy8IexP7c8JEmsUA7odA="
   # GPG_KEY_NAME
   secure: "hrYmjPWqRtu82wnx7Zvh9MKTGwqGKOnOksVEIq8xq5nca07Fde6dVhkgM7CQyOG880H+W7vVtL2ehZJmbiS5GZtx7QTlLwjeNH8ic31Abj6kno8nJ++AeLAIadXoPYiusBOkqfe+joNuiqW2K+O1UUmrWTAVrhhh+Z4qkWkyH+GhLvoOB27I0aX8+ZhLDrko/jJfBN442OUSvVN6NPhg2R9bxMPPgerkf1lDJi4e3eAKUXvIR5QjFKfZ3MHsw7T8ZcIEySUqekOetZZKEgyD1vkSDrsusVv+WSmPVJHvk+DCN8z3yprFOAX64j2mWZyVikxhQgCaTDPTaClJEeI/kHZPWr1ZtDohRpsq3ahHbVNfNZPplQ6cAWSK9XhaAzHPpT6zz6MyIK2ykmoGJ7JGuAZSkV/FveFF+EBLo7zcQxHB27Wh2a9DyuPLvHcSXSbaXZTGiHE3sWfR8Y0ocEuHwhL/HnHeRqi15c6aQ0R3/2wnwmKPP8sUBGWf6c6c4IWIm3sDAbJ/CGtwx3WuGbinxLyyaaETq76/+qQoa9Z6Qt/pHBLwUgCHsNjMKEcPVUGFpsu7G+r8O06w1Tx1X557R+Q0H1dXY5KC4i1o/Xe8olCZo12ltKQMyEzUI0cj09EMc5EXkPeggbEcQ5vrbvtyVZWjge5LbaJ6AOgsDAAp2Pc="
   # GPG_PASSPHRASE
   secure: "cUNpOdnmwSt2MBvDwBHJ17Y1fKQI41+m2IHmHqxpMurv67JiO1yexqJFLudqYMeHtc9hJGBgHDnuGUkx8A/33nYohx+1YEyr7xs2Vhp4KwzjElEUZuwuR7DCDbq7dtmxZ8X8x48lUxxJZsrCuJQMvHt5c7AcPaPQYli+nDT9gByEoMPxO7/ORv3k10AGDdREJU3HjnAjsHEvF16gTe2VUilx4NxG6ePjy6HI5YRuAUeiAQjToxJQJT8QrTDlaEjYzL4vHXC4XjxmcD2+vl1FmFMoywadmtYESHYYfYoxoETbWJP2Q0zxKmyrP90h8WZ9Otp+0irJJZ36QkS+6nvq187mcBsWzqjNtEaFZtSkh4bTtdWFWv1lj4icSmMCVW7hrym02KaaGu8J6tNeWHlgfrAppkiwhI6E1xmasaiYY686UPmy3+2NjVXUWnm5SLsAcVzRwGdyDI9BeTVn/CWjSgtN1KXz2HXnlsdBgwIQE3oo6pUPsHJIpqyrxJI2aUVWJAHpWkWUYI0xAAjZYmV954BPN5ZihjXucFYQN1duKeSrNaGfgWe5W3ZzusDXPSdKkC9EZU3fjuVBTtaFrP8GJt5RMyA9dOwikSEQvzZujce3CA0kl0BtkARMzIwklzPrYtqN7Nm/7xZm2St33Aj6X1c0vOYENQZSfOK+DfpmPZc="

before_install:
  #- sudo apt-get update -q
  #- sudo apt-get install gnupg2
 
install: 
  #- sudo echo "default-key $GPG_KEY_NAME" >> ~/.gnupg/gpg.conf
  - mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
   
script: mvn test -P !build-extras -B
   
after_success:
  - build/before-deploy.sh
  - build/deploy.sh
  
# configure notifications (email, IRC, campfire etc)
# check results at https://webchat.freenode.net/
notifications:
  irc: "irc.freenode.org#deepviolet"