language: java

jdk: oraclejdk8

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

#deploy only on tags of the form v1.2.3
#
#deploy:
#  on:
#    tags: true
#    condition: "$TRAVIS_TAG =~ ^v[0-9].[0-9].[0-9]$"

cache:
  directories:
    - ~/.m2/repository
 
before_install:
  - sudo apt-get update -q
  - sudo apt-get install gnupg2
  #- sudo apt-get install gnupg-agent
  #- sudo apt-get install libgcrypt11
 
install: 
  #- sudo echo "default-key $GPG_KEY_NAME" >> ~/.gnupg/gpg.conf
  - mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:   
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script: mvn test -P !build-extras -B
   
after_success:
  - build/before-deploy.sh
  - build/deploy.sh
  
# configure notifications (email, IRC, campfire etc)
# check results at https://webchat.freenode.net/
notifications:
  irc: "irc.freenode.org#deepviolet"
  template:
      - '%{repository_slug}#%{build_number} (%{branch}) %{message} %{build_url}'