language: java

jdk: oraclejdk8

cache:
  directories:
    - ~/.m2/repository

env:
  global:
   # GH_TOKEN
   secure: "ejbUqrRdKFPHVGXVDdu15z5GYS6sY2h+UQT48Jvr6p6CC3Ta6sQajvRzBc3DQP+KKXyiFryNN5fBhF0UezoElQ1V1eD4I82JDqF7HKmpk1nJnoLkdYQjbIEvTv7fRSs+IGpL62zYZUMR2/Iy+V32qECjUCEvnCHPRHaTnKDUlegGDEuBKyb7YGEzzxMRQWXJkd2xrR0tcaGYArtnAXtOH4sYSATFZB7UDiq1hRvX4eB5KVyKEVpHM45gnhccoGXkeeTy3m5KWxHypF7tK3pbe1mJejX4EURCER/hGrcS8xNzRmBbAhuk/KwAUCGo7AjOa5g301wp6n61Aen5sG4g+NMCjkUc0GmCDZ1/k/rH+DhXPmhI0X0cMG/BKtCdVbYDtFh03RCjwfxvxr3kjoXgz/rGBA14otzwnf2Ct9Q2VYiBFKCFm254fFgdlSu9DN53kyUIGSwXXxtj7+kExatpIMIQ22wiloWdZUQFk+J8eOGdfUzBgPc3Xe/HuNGI+G/Y6RWVhXY49xOmn6kHNSGj4ajyki8U0QthrEJ54mTQ+ZSAVtTx1BxGbOpN4MTg4UhLNv0vATi+a1lESCfu7Sn+XRRULPryeHFgSeLIsRxNjMics2Eg3KnDmKH8XOtmxj3v5WigZ+kI159C1h9nSJ4KvdrFvY8K/qXyM2lL77Fh4Bg="
   # OSSRH_USER
   secure: "LZLEMadHaJf9Cvl99vRAqt+e8gA/sfJLwokhV5+qQKF18tVUoP/HKkmg6hvbYRYS3YqKKLnC6GXmEZFnbbLzgk+eZWWu4jtLSzbzip78NVkZFVDHznAZQZldSwTpIkmDAjY/xekdXCjU1hAuXlHxfLFdf3SwsgUjXiLcgT4Mky84MqvKcH0o054awQ0NK2Y8Oxq6NAz0nt5ol7cMmRE/hhOZztShlULlKRjP3hHMmDigQlhobMvc7sZSfmC5DrOYPZQmZWlN0u7G8ONITM0gR4DAPaNpgYRLYlLLSn7tK4U0HDd97msWQwuui3mAwRL91rQ6dzAICvYQGlz+z2ZEROHFSDYByyLXL3W8LNY0KnMzMMRqhi02U2q9+PKp3j083gcIwYwhChPvqL/uwxDNUW3RsXylzGwvKVsIFFWVtHh7CsvgJaOyYEYtDnaHTpLcqGyJgFaxrqJZeyBB7TVIks8aIhXvLFZCM8RbkF90o/rBJ4U3cN5iwyIulCZ3Qv/+embVW6M86rz4tnWTf0aHE4hh/zCZ2GPrdCQPz6ZIBjVWUtSe6IvCYP+64LCgTi8aVFpga0Vnfz/w2DxXkRIoPF5jQtoOdMwzVh6e7tl1xmP9Q4yJTLeHbSx1b8h56Rx3RwzAxSmIeJ/9AqgUS2l9+EegCpKc+Jwy82vZKGO6KzA="
   # OSSRH_PASS
   secure: "ajZHBBCYFAQsehG8qPet01mgCSMPPKhLQeHbDFj/EBJ3/Zdij1/hkF6jY+0H5c52ui1J0PX/XggtPYytC607mjTRTrt009dhJ6180lLKhWxM8o6n1X+whzZMwOO1a/0YXedhjLjfkxU4XOkd2LtT16BLUTXQ83/vC5kHOqlc4ZlfrBFflHZuxB3DgB3UNYAiGkY5k6q0ECLeG3DkR/NIjOvufFijbS47ikDr0fhNfYjU/Ai1H3DPhO3XVXTkU85GOi31jVdHeEttmczmYiILUgmuCKLwTsMwrBjYSnLms2TpsqVD26doinw6xzGHHyhCvDJb0AF/IkJ8o6i5cbAEnSAfn3l8DsOxbvz0xxgTA7d7cUZ2pwlCDQDsNMSzfAh3tFCHM+D5DPC1PKwgfr9OVsnQo+9FPaaLDzr0rrSNv988R98vB1T+kcfV/b3QeA7AA+A0IstuevoR/ok9jOfyF5ST0tBORPW5PKEkf3iJCZiSbo1aU/fNhC8Sf+65j7rMJ2z7aInCcZhjrGwLDVNkg1zQZCso6p7op160V0i/r4kEbCWnkvxBHym4zGlQrrUMtigzjMFt4/R9KwITuXXSKUishbngiLlLDTd1rbv/jwBpJL+6C5KZExZGWnIdvDGoCURcGfNCH75aAo746aYQLNrMmbgD9JP/H5w8PRFyLHk="
   # OPENSSL_ENCRYPT_KEY
   secure: "pUMsNcIJHtIkaRyYKv3jGH5+Oz+LAv2SYqDb/zORJFvBi/T3dFy3qw8HLRPl+lr7a/VrBanrpJIGrRDIChjt9uWSjs/JYRQ+AqhHZzz4jhFB2yhULz1rdiRlh1dor8BnaXq4MP5ofzLWKz3V5YRq2EUBFUO+RHjUr72lSyvIWmJB2B4lweIRLh9TRI04vWGGfrU/ZwS6764ImkmhdWFuBHWofTUt8RBQ6ibRe33uRLY0jv0LAmNhXpdKh/fiDllncuh27zUg/Nviv7frdBGsKdtvGqUQFJuk7wgB6uajrAkBw9sg4AQRAFqbIdkECTNmgFRfpilfKMYmT250PbAU+MWsYzbxUSAEZC+bNAWjkpLCmXNSX8QlnbdI+l84cPXOy9VFnOiRfaNDI+2gHyuK+JgkdmQ/hE4MWZLrgneAKF1ffSB8WQnUbJVx78/1I4WATQoFqLm3LcB/9xMZ9/ojCuF6MPl/u/9/WdEzSj1bq3dZ/VfNEFBv+8D/8MyvxR4+GMBgmUfmJR2yHJwFMofI4MnF2VXqeJLmO5WYhWNK/tvBDUDrR2dDmvYoPZm3tgt7Xya77sw1FzVH8jQ4QH05t2kfGwbifDnT5M4LnnE91yL+qYU+89fzWAlaEqSkohQ2E3FywYb+BSDj1G3SE8U+3M00dGOYagkjQNzZlYHBDUs="
   # GPG_KEY_NAME
   secure: "CKI5F9d+bhqgsWwKBcKdSR4vpUdhMLLThcCg2lwx6TSc3jOXBYD+I8Hfz9Icuvfa9FLZfSv1ZMS+zwbMZvlN6B6/pHVCTP+qOP3Z6z4nnO/mKUvrX68GwXcM2p1tZknopFj7a60eoNUl2vLNISv5EgFovSlvHBGnAfbVXdBotR1VgPkLymrHboFPsTXfNgP24jXSaZDyPNodMU4c86YZHw1vRO/yB6XZ7K5KHK4uzTXQpgPUYj/06BSqr+w+pIs4Q1DXTBjhxR7+ddNLdGKC/Q4J/2bJzqxeJUHalEDmbahcE94Se1zKbeTydQTGA5QnO8ekNQ6eNIH1xM59TK1JOmKtVwSrqrTilVrwiNWPO0ZuISwNubXt94mtLZ2BK6rWfoT9d2a4KTgApaJw1+U18vz8noc6cVD6V9gPmqAVieKY86wUNNim9BRGIgfPANnwD44QYBTzH2Qz9v28EuC/E8IYK3S7kOuSD4ao0LteUt63/3LxvUY9BgegT5SNZF4kvzWH9msriW4S6AW0KHhDcSvZsfKvA04Hk6y4SgX7HF/RoDW51ccs9iN+wQY+9mK1/DcOGiqwZzEpX0IqFj+TGdbY0+nlS+ibFFVQ6OYGmmyKmt2YTgIuEYVlx2dVgvbqI9pEn1gka+ejltj6YcSGeM1v0p50D14N3POFib7u6YA="  
   # GPG_PASSPHRASE
   secure: "cUNpOdnmwSt2MBvDwBHJ17Y1fKQI41+m2IHmHqxpMurv67JiO1yexqJFLudqYMeHtc9hJGBgHDnuGUkx8A/33nYohx+1YEyr7xs2Vhp4KwzjElEUZuwuR7DCDbq7dtmxZ8X8x48lUxxJZsrCuJQMvHt5c7AcPaPQYli+nDT9gByEoMPxO7/ORv3k10AGDdREJU3HjnAjsHEvF16gTe2VUilx4NxG6ePjy6HI5YRuAUeiAQjToxJQJT8QrTDlaEjYzL4vHXC4XjxmcD2+vl1FmFMoywadmtYESHYYfYoxoETbWJP2Q0zxKmyrP90h8WZ9Otp+0irJJZ36QkS+6nvq187mcBsWzqjNtEaFZtSkh4bTtdWFWv1lj4icSmMCVW7hrym02KaaGu8J6tNeWHlgfrAppkiwhI6E1xmasaiYY686UPmy3+2NjVXUWnm5SLsAcVzRwGdyDI9BeTVn/CWjSgtN1KXz2HXnlsdBgwIQE3oo6pUPsHJIpqyrxJI2aUVWJAHpWkWUYI0xAAjZYmV954BPN5ZihjXucFYQN1duKeSrNaGfgWe5W3ZzusDXPSdKkC9EZU3fjuVBTtaFrP8GJt5RMyA9dOwikSEQvzZujce3CA0kl0BtkARMzIwklzPrYtqN7Nm/7xZm2St33Aj6X1c0vOYENQZSfOK+DfpmPZc="

before_install:
  - sudo apt-get update -q
  - sudo apt-get install gnupg2
 
install: 
  #- sudo echo "default-key $GPG_KEY_NAME" >> ~/.gnupg/gpg.conf
  - mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
   
script: mvn test -P !build-extras -B
   
after_success:
  - build/before-deploy.sh
  - build/deploy.sh
  
# configure notifications (email, IRC, campfire etc)
# check results at https://webchat.freenode.net/
notifications:
  irc: "irc.freenode.org#deepviolet"