language: java
jdk:
- oraclejdk8
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   secure: "IzAX6GIiDdMGOC/qm7BJ9O54XWikdTOpNvmKbGpcjzh7flSSRNJY+gO3yC3+va5G87MnobFc99GYsGQHwLp60cSDb6IrGt1mcClSuz01JDkuaKevnpUeHns9D7Kxvrqr6sV5W4yUtU+cN4wfKbMEtGlSZ3Lcy2mtSL5PdKQ/aQQKrs8cHARtTPQ6+f8UkYuvVFkI3qEQIo4ogd0dAvmvbyJPg1ERUIa+2+IfUgKEpfHMSWHBAZqvYsTQbmuagXFZTMRhAej/UsWgVKenwbqVt3dpNwchdyUp7KmYEBcla6ToooS8FsqRPTulzulcGwrfjtb9jvtKsdRNuFej+gZQFMz96Pz8nwb8E0jNHKrkX+3iY3lFL36wi4sW+C7fmKji9PRHQ9masFRiCcitr9rzVmwRmKggoHNAEabAS7Di4YxJParIFpt97EuAlhn5Sc4V64UhkdM2SGzSKR0utI0aKqTj9UQWIUb/+Ldxi/R7YisFqvMBer1KK9CiwRA4bgksE0bM+aWxYVsB58sxfCh6/rRbhLb+3bgHijOv8quA+JhOmTNaOrNbPeVWKmmtrGngP9QFRPTN1RvGClkExUgueUkDkjcAjo8o3QXXsaeEtJjfuiZvmiVl21SPe/a4B5yiH811Dz0VJ84B9mf9aPF/R8Ue0bP/1nkJpNplnysvJsU="
   # The next declaration is the encrypted GH_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   secure: "ejbUqrRdKFPHVGXVDdu15z5GYS6sY2h+UQT48Jvr6p6CC3Ta6sQajvRzBc3DQP+KKXyiFryNN5fBhF0UezoElQ1V1eD4I82JDqF7HKmpk1nJnoLkdYQjbIEvTv7fRSs+IGpL62zYZUMR2/Iy+V32qECjUCEvnCHPRHaTnKDUlegGDEuBKyb7YGEzzxMRQWXJkd2xrR0tcaGYArtnAXtOH4sYSATFZB7UDiq1hRvX4eB5KVyKEVpHM45gnhccoGXkeeTy3m5KWxHypF7tK3pbe1mJejX4EURCER/hGrcS8xNzRmBbAhuk/KwAUCGo7AjOa5g301wp6n61Aen5sG4g+NMCjkUc0GmCDZ1/k/rH+DhXPmhI0X0cMG/BKtCdVbYDtFh03RCjwfxvxr3kjoXgz/rGBA14otzwnf2Ct9Q2VYiBFKCFm254fFgdlSu9DN53kyUIGSwXXxtj7+kExatpIMIQ22wiloWdZUQFk+J8eOGdfUzBgPc3Xe/HuNGI+G/Y6RWVhXY49xOmn6kHNSGj4ajyki8U0QthrEJ54mTQ+ZSAVtTx1BxGbOpN4MTg4UhLNv0vATi+a1lESCfu7Sn+XRRULPryeHFgSeLIsRxNjMics2Eg3KnDmKH8XOtmxj3v5WigZ+kI159C1h9nSJ4KvdrFvY8K/qXyM2lL77Fh4Bg="
addons:
  coverity_scan:
    project:
      name: spoofzu/DeepViolet
      description: DeepViolet SSL/TLS Introspection Tool 
    notification_email: milton.smith.rr@gmail.com
    build_command_prepend: mvn clean
    build_command: mvn install
    branch_pattern: master
